package com.nicai.entity;

import lombok.Data;

import java.util.Date;

@Data
public class MyTable1 {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_table0.id
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_table0.name
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_table0.create_time
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_table0.update_time
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    private Date updateTime;

}