package com.nicai.mapper;

import com.nicai.entity.MyTable1;
import org.springframework.stereotype.Repository;

@Repository
public interface MyTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_table0
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    int insert(MyTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_table0
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    MyTable1 selectByPrimaryKey(Long id);

}