package com.nicai.mapper;

import com.nicai.entity.MyTable0;
import org.springframework.stereotype.Repository;

@Repository
public interface MyTable0Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_table0
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    int insert(MyTable0 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_table0
     *
     * @mbggenerated Mon Apr 27 14:29:52 CST 2020
     */
    MyTable0 selectByPrimaryKey(Long id);

}